# Generated by Django 6.0.7 on 2026-07-27 01:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Category Name')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True, verbose_name='Slug')),
                ('excerpt', models.TextField(help_text='Short overview displayed in cards and search results.', verbose_name='Excerpt / Summary')),
                ('content', models.TextField(verbose_name='Full Article Content')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='news/', verbose_name='Featured Image')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20, verbose_name='Publication Status')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Publication Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_articles', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='cms.category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'News Article',
                'verbose_name_plural': 'News Articles',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OfficialBulletin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Bulletin Title')),
                ('bulletin_type', models.CharField(choices=[('DAILY_SYNOPTIC', 'Daily Synoptic Bulletin'), ('MONTHLY_CLIMATE', 'Monthly Climate Outlook'), ('MARINE', 'Marine Bulletin'), ('SEISMIC', 'Seismic Event Summary'), ('SPECIAL', 'Special Hydrometeorological Report')], default='DAILY_SYNOPTIC', max_length=30, verbose_name='Bulletin Type')),
                ('pdf_file', models.FileField(upload_to='bulletins/', verbose_name='PDF Document File')),
                ('summary', models.TextField(blank=True, verbose_name='Summary / Overview')),
                ('publication_date', models.DateField(verbose_name='Publication Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulletins', to=settings.AUTH_USER_MODEL, verbose_name='Uploaded By')),
            ],
            options={
                'verbose_name': 'Official Bulletin',
                'verbose_name_plural': 'Official Bulletins',
                'ordering': ['-publication_date', '-created_at'],
            },
        ),
    ]
