# Generated by Django 5.1 on 2026-08-08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_newsarticleinlineimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticleInlineAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='news/content/documents/', verbose_name='Inline Supporting File')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Document Title')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inline_attachments', to='cms.newsarticle', verbose_name='Article')),
            ],
            options={
                'verbose_name': 'Inline Article Attachment',
                'verbose_name_plural': 'Inline Article Attachments',
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
