# Generated by Django 6.0.7 on 2026-08-06 08:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Department Name')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Department Code')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DownloadCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Category Name')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Display Order')),
            ],
            options={
                'verbose_name': 'Download Category',
                'verbose_name_plural': 'Download Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StaffLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Level Name')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Code')),
                ('rank', models.PositiveSmallIntegerField(default=0, help_text='Lower number = higher rank (1 = most senior)', verbose_name='Rank Order')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Staff Level',
                'verbose_name_plural': 'Staff Levels',
                'ordering': ['rank', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DownloadableFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags for search', max_length=500, verbose_name='Tags')),
                ('file', models.FileField(upload_to='hr/downloads/', verbose_name='File')),
                ('file_type', models.CharField(choices=[('PDF', 'PDF Document'), ('EXCEL', 'Excel Spreadsheet'), ('WORD', 'Word Document'), ('ZIP', 'ZIP Archive'), ('IMAGE', 'Image'), ('OTHER', 'Other')], default='OTHER', max_length=10, verbose_name='File Type')),
                ('version', models.CharField(blank=True, default='1.0', max_length=30, verbose_name='Version')),
                ('access_level', models.CharField(choices=[('PUBLIC', 'Public (Visible on public website)'), ('STAFF', 'Staff Only (Internal access required)')], default='STAFF', max_length=10, verbose_name='Access Level')),
                ('download_count', models.PositiveIntegerField(default=0, verbose_name='Download Count')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_downloads', to=settings.AUTH_USER_MODEL, verbose_name='Uploaded By')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='hr.downloadcategory', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Downloadable File',
                'verbose_name_plural': 'Downloadable Files',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_number', models.CharField(max_length=30, unique=True, verbose_name='Employee Number')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='hr/photos/', verbose_name='Photo')),
                ('full_name', models.CharField(max_length=200, verbose_name='Full Name')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, verbose_name='Gender')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('nationality', models.CharField(default='Timorese', max_length=100, verbose_name='Nationality')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Phone Number')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email Address')),
                ('position', models.CharField(max_length=150, verbose_name='Position / Job Title')),
                ('employment_type', models.CharField(choices=[('PERMANENT', 'Permanent'), ('CONTRACT', 'Contract'), ('CONSULTANT', 'Consultant'), ('INTERN', 'Intern')], default='PERMANENT', max_length=20, verbose_name='Employment Type')),
                ('salary_grade', models.CharField(blank=True, max_length=50, verbose_name='Salary Grade')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('contract_end_date', models.DateField(blank=True, null=True, verbose_name='Contract End Date')),
                ('employment_status', models.CharField(choices=[('ACTIVE', 'Active'), ('ON_LEAVE', 'On Leave'), ('RETIRED', 'Retired'), ('RESIGNED', 'Resigned'), ('TERMINATED', 'Terminated')], default='ACTIVE', max_length=20, verbose_name='Employment Status')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='hr.department', verbose_name='Department')),
                ('user_account', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_profile', to=settings.AUTH_USER_MODEL, verbose_name='Linked User Account')),
                ('staff_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='hr.stafflevel', verbose_name='Staff Level / Grade')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'ordering': ['full_name'],
            },
        ),
        migrations.AddField(
            model_name='department',
            name='head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads_department', to='hr.employee', verbose_name='Head of Department'),
        ),
        migrations.CreateModel(
            name='EmployeeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Document Title')),
                ('document_type', models.CharField(choices=[('CONTRACT', 'Contract'), ('ID', 'Identification'), ('CERTIFICATE', 'Certificate'), ('OTHER', 'Other')], default='OTHER', max_length=20, verbose_name='Document Type')),
                ('file', models.FileField(upload_to='hr/documents/', verbose_name='File')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='hr.employee', verbose_name='Employee')),
            ],
            options={
                'verbose_name': 'Employee Document',
                'verbose_name_plural': 'Employee Documents',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
