# Generated by Django 6.0.7 on 2026-07-27 01:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Station Name')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Station Code')),
                ('municipality', models.CharField(choices=[('AILEU', 'Aileu'), ('AINARO', 'Ainaro'), ('BAUCAU', 'Baucau'), ('BOBONARO', 'Bobonaro'), ('COVA_LIMA', 'Cova Lima'), ('DILI', 'Dili'), ('ERMERA', 'Ermera'), ('LAUTEM', 'Lautem'), ('LIQUICA', 'Liquica'), ('MANATUTO', 'Manatuto'), ('MANUFAHI', 'Manufahi'), ('OECUSSE', 'Oecusse'), ('VIQUEQUE', 'Viqueque')], default='DILI', max_length=30, verbose_name='Municipality')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Latitude')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Longitude')),
                ('elevation', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Elevation (m)')),
                ('station_type', models.CharField(choices=[('AWS', 'Automated Weather Station (AWS)'), ('SYNOPTIC', 'Synoptic Station'), ('AGROMET', 'Agrometeorological Station'), ('HYDROMET', 'Hydrometeorological Station'), ('SEISMIC', 'Seismic Monitoring Station')], default='AWS', max_length=20, verbose_name='Station Type')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('MAINTENANCE', 'Under Maintenance'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20, verbose_name='Status')),
                ('installed_date', models.DateField(blank=True, null=True, verbose_name='Installed Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Weather Station',
                'verbose_name_plural': 'Weather Stations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EarlyWarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Warning Title')),
                ('severity', models.CharField(choices=[('info', 'Information / Advisory'), ('warning', 'Warning (Orange Alert)'), ('danger', 'Severe Hazard Alert (Red Alert)')], default='warning', max_length=20, verbose_name='Severity Level')),
                ('region', models.CharField(help_text='e.g., Viqueque & Lautem Municipalities, All Coastal Areas', max_length=255, verbose_name='Affected Region / Municipalities')),
                ('description', models.TextField(verbose_name='Detailed Advisory Content')),
                ('valid_from', models.DateTimeField(verbose_name='Valid From')),
                ('valid_to', models.DateTimeField(verbose_name='Valid Until')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warnings', to=settings.AUTH_USER_MODEL, verbose_name='Issued By')),
            ],
            options={
                'verbose_name': 'Early Warning',
                'verbose_name_plural': 'Early Warnings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WeatherObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Temperature (°C)')),
                ('humidity', models.IntegerField(blank=True, null=True, verbose_name='Humidity (%)')),
                ('rainfall_mm', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='Rainfall (mm)')),
                ('wind_speed_kmh', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Wind Speed (km/h)')),
                ('wind_direction', models.CharField(blank=True, max_length=20, verbose_name='Wind Direction')),
                ('pressure_hpa', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='Pressure (hPa)')),
                ('wave_height_m', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Wave Height (m)')),
                ('condition_text', models.CharField(blank=True, max_length=100, verbose_name='Condition Description')),
                ('recorded_at', models.DateTimeField(verbose_name='Recorded At')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observations', to=settings.AUTH_USER_MODEL, verbose_name='Recorded By')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='weather.weatherstation', verbose_name='Station')),
            ],
            options={
                'verbose_name': 'Weather Observation',
                'verbose_name_plural': 'Weather Observations',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='WeatherForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipality', models.CharField(choices=[('AILEU', 'Aileu'), ('AINARO', 'Ainaro'), ('BAUCAU', 'Baucau'), ('BOBONARO', 'Bobonaro'), ('COVA_LIMA', 'Cova Lima'), ('DILI', 'Dili'), ('ERMERA', 'Ermera'), ('LAUTEM', 'Lautem'), ('LIQUICA', 'Liquica'), ('MANATUTO', 'Manatuto'), ('MANUFAHI', 'Manufahi'), ('OECUSSE', 'Oecusse'), ('VIQUEQUE', 'Viqueque')], max_length=30, verbose_name='Municipality')),
                ('forecast_date', models.DateField(verbose_name='Forecast Date')),
                ('temp_min', models.IntegerField(verbose_name='Min Temperature (°C)')),
                ('temp_max', models.IntegerField(verbose_name='Max Temperature (°C)')),
                ('condition', models.CharField(max_length=100, verbose_name='Condition')),
                ('icon', models.CharField(default='cloud-sun', help_text='Bootstrap icon name e.g., sun, cloud-rain, cloud-lightning, cloud-sun', max_length=50, verbose_name='Icon Class (Bootstrap)')),
                ('rain_probability', models.IntegerField(default=0, verbose_name='Rainfall Probability (%)')),
                ('wind_summary', models.CharField(blank=True, max_length=50, verbose_name='Wind Summary')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forecasts', to=settings.AUTH_USER_MODEL, verbose_name='Issued By')),
            ],
            options={
                'verbose_name': 'Weather Forecast',
                'verbose_name_plural': 'Weather Forecasts',
                'ordering': ['forecast_date', 'municipality'],
                'unique_together': {('municipality', 'forecast_date')},
            },
        ),
    ]
