# Generated by Django 6.0.7 on 2026-08-05 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_phase3_live_stations'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherobservation',
            name='battery_voltage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Battery Voltage (V)'),
        ),
        migrations.AddField(
            model_name='weatherobservation',
            name='sea_surface_temp',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Sea Surface Temp (°C)'),
        ),
        migrations.AddField(
            model_name='weatherobservation',
            name='solar_radiation',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='Solar Radiation (W/m²)'),
        ),
        migrations.AddField(
            model_name='weatherobservation',
            name='wind_gust_kmh',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Max Wind Gust (km/h)'),
        ),
        migrations.AlterField(
            model_name='weatherobservation',
            name='tide_level_mm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Tide Level (mm)'),
        ),
    ]
