# Generated by Django 6.0.7 on 2026-08-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_weatherobservation_battery_voltage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherobservation',
            name='temperature',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Temperature (Â°C)'),
        ),
        migrations.AlterField(
            model_name='weatherobservation',
            name='humidity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Humidity (%)'),
        ),
        migrations.AlterField(
            model_name='weatherobservation',
            name='rainfall_mm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Rainfall (mm)'),
        ),
        migrations.AlterField(
            model_name='weatherobservation',
            name='wind_speed_kmh',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Wind Speed (km/h)'),
        ),
        migrations.AlterField(
            model_name='weatherobservation',
            name='pressure_hpa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Pressure (hPa)'),
        ),
        migrations.AlterField(
            model_name='weatherobservation',
            name='solar_radiation',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Solar Radiation (W/mÂ²)'),
        ),
        migrations.AlterField(
            model_name='weatherobservation',
            name='wind_gust_kmh',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Max Wind Gust (km/h)'),
        ),
        migrations.AlterField(
            model_name='weatherobservation',
            name='sea_surface_temp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Sea Surface Temp (Â°C)'),
        ),
    ]
