# Generated by Django 6.0.7 on 2026-08-09 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0004_preserve_two_decimal_observation_telemetry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherobservation',
            name='sea_surface_temp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Sea Surface Temp (°C)'),
        ),
        migrations.AlterField(
            model_name='weatherobservation',
            name='solar_radiation',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Solar Radiation (W/m²)'),
        ),
        migrations.AlterField(
            model_name='weatherobservation',
            name='temperature',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Temperature (°C)'),
        ),
    ]
