# Generated by Django 6.0.7 on 2026-08-25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0009_convert_api_wind_gusts_to_kmh'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficialForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Forecast Title')),
                ('forecast_period', models.CharField(choices=[('1-day', '1-Day Forecast'), ('3-day', '3-Day Forecast'), ('7-day', '7-Day Forecast')], max_length=10, verbose_name='Forecast Period')),
                ('valid_from', models.DateField(verbose_name='Valid From')),
                ('valid_to', models.DateField(verbose_name='Valid Until')),
                ('coverage', models.CharField(default='Timor-Leste', help_text='e.g. Timor-Leste, northern coast, or selected municipalities', max_length=255, verbose_name='Coverage Area')),
                ('summary', models.TextField(verbose_name='Forecast Summary')),
                ('notes', models.TextField(blank=True, verbose_name='Meteorologist Notes')),
                ('image', models.ImageField(blank=True, null=True, upload_to='official_forecasts/images/', verbose_name='Forecast Image')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='official_forecasts/files/', verbose_name='Supporting File')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=12, verbose_name='Publication Status')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Published At')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='official_forecasts_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='official_forecasts_published', to=settings.AUTH_USER_MODEL, verbose_name='Published By')),
            ],
            options={
                'verbose_name': 'Official Forecast',
                'verbose_name_plural': 'Official Forecasts',
                'ordering': ['-published_at', '-created_at'],
                'indexes': [models.Index(fields=['status', 'forecast_period', '-valid_from'], name='official_forecast_public_idx')],
                'constraints': [
                    models.CheckConstraint(condition=models.Q(('forecast_period__in', ['1-day', '3-day', '7-day'])), name='official_forecast_period_valid'),
                    models.CheckConstraint(condition=models.Q(('status__in', ['draft', 'published', 'archived'])), name='official_forecast_status_valid'),
                    models.CheckConstraint(condition=models.Q(('valid_to__gte', models.F('valid_from'))), name='official_forecast_validity_range'),
                ],
            },
        ),
    ]
