# Generated by Django 6.0.7 on 2026-08-25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0010_officialforecast'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficialForecastAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='official_forecasts/attachments/', verbose_name='Supporting File')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='File Title')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Display Order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('forecast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='weather.officialforecast', verbose_name='Official Forecast')),
            ],
            options={
                'verbose_name': 'Official Forecast Attachment',
                'verbose_name_plural': 'Official Forecast Attachments',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OfficialForecastImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='official_forecasts/gallery/', verbose_name='Image')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Image Caption')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Display Order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('forecast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='weather.officialforecast', verbose_name='Official Forecast')),
            ],
            options={
                'verbose_name': 'Official Forecast Image',
                'verbose_name_plural': 'Official Forecast Images',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
